name: ChampionsList

options:
  postGenCommand: pod install
  indentWidth: 4
  tabWidth: 4
  xcodeVersion: "14.1.0"

settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 13

targets:
  
  ChampionsList:
    type: application
    platform: iOS

    sources:
      - path: ChampionsList/
      - path: "ChampionsList/Generated/R.generated.swift"
        optional: true
        type: file

    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        DISPLAYNAME: League of Legends Champions
        HOST: api.github.com
        SCHEME: https
        INFOPLIST_FILE: ChampionsList/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.helios.championsList

    preBuildScripts:
        - name: R.swift script
          script: |
            "$PODS_ROOT/R.swift/rswift" generate "$SRCROOT/ChampionsList/Generated/R.generated.swift"
          outputFiles:
          - $SRCROOT/ChampionsList/Generated/R.generated.swift
            
  ChampionsListTests:
    type: bundle.unit-test
    platform: iOS

    sources:
      - path: ChampionsListTests

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.championsListTests
