name: LeagueOfLegendsChampions

options:
  postGenCommand: pod install
  indentWidth: 4
  tabWidth: 4
  xcodeVersion: "14.1.0"

settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 13
    TARGETED_DEVICE_FAMILY: 1

targets:
  
  LeagueOfLegendsChampions:
    type: application
    platform: iOS

    sources:
      - path: LeagueOfLegendsChampions/
      - path: "LeagueOfLegendsChampions/Generated/R.generated.swift"
        optional: true
        type: file

    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        INFOPLIST_KEY_CFBundleDisplayName[sdk=iphoneos*]: League of Legends Champions
        CURRENT_NAME: League of Legends Champions
        HOST: us-central1-whatslol-1460f.cloudfunctions.net
        SCHEME: https
        INFOPLIST_FILE: LeagueOfLegendsChampions/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.helios.LeagueOfLegendsChampions

    preBuildScripts:
        - name: R.swift script
          script: |
            "$PODS_ROOT/R.swift/rswift" generate "$SRCROOT/LeagueOfLegendsChampions/Generated/R.generated.swift"
          outputFiles:
          - $SRCROOT/LeagueOfLegendsChampions/Generated/R.generated.swift
            
  LeagueOfLegendsChampionsTests:
    type: bundle.unit-test
    platform: iOS

    sources:
      - path: LeagueOfLegendsChampionsTests

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.LeagueOfLegendsChampionsTests
