name: LeagueOfLegendsChampions

packages:
  SDWebImage:
    url: https://github.com/SDWebImage/SDWebImage
    majorVersion: 5.0.0
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 13
    TARGETED_DEVICE_FAMILY: 1

targets:
  LeagueOfLegendsChampions:
    type: application
    platform: iOS
    sources:
      - path: LeagueOfLegendsChampions/
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        INFOPLIST_KEY_CFBundleDisplayName[sdk=iphoneos*]: League of Legends Champions
        CURRENT_NAME: League of Legends Champions
        HOST: us-central1-whatslol-1460f.cloudfunctions.net
        SCHEME: https
        INFOPLIST_FILE: LeagueOfLegendsChampions/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.helios.LeagueOfLegendsChampions
    dependencies:
      - package: SDWebImage

  LeagueOfLegendsChampionsTests:
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: LeagueOfLegendsChampions
    sources:
      - path: LeagueOfLegendsChampionsTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.LeagueOfLegendsChampionsTests
        INFOPLIST_FILE: LeagueOfLegendsChampionsTests/Info.plist

schemes:
  LeagueOfLegendsChampions:
    build:
      targets:
        LeagueOfLegendsChampions: all
    run:
      config: Debug
      debugEnabled: true
    test:
      config: Debug
      language: "Portuguese (Brasil)"
      regison: "Brazil"
      gatherCoverageData: true
      coverageTargets:
        - LeagueOfLegendsChampions 
      targets:
        - name: LeagueOfLegendsChampionsTests
          parallelizable: true