# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: maci7

    steps:
    - uses: actions/checkout@v3
    - name: Build and Test
      run: |
        xcodegen
        xcodebuild build-for-testing -project LeagueOfLegendsChampions.xcodeproj -scheme LeagueOfLegendsChampions -destination generic/platform=iOS

